import io
import sys

_INPUT = """\
6
..........
..........
..........
..........
...######.
...######.
...######.
...######.
..........
..........
..........
..#.......
..........
..........
..........
..........
..........
..........
..........
..........
##########
##########
##########
##########
##########
##########
##########
##########
##########
##########
"""

sys.stdin = io.StringIO(_INPUT)
case_no=int(input())  
for __ in range(case_no):
  S=[input() for _ in range(10)]
  for i in range(10):
    for j in range(10):
      if S[i][j]=='#': t=(i,j)
  for i in reversed(range(10)):
    for j in reversed(range(10)):
      if S[i][j]=='#': s=(i,j)
  print(s[0]+1,t[0]+1)
  print(s[1]+1,t[1]+1)